### ISSUE TITLE
Models in the 0.2 directory should use the proper spec?

### ISSUE THREAD

**Issue by Alos** [in-toto/in-toto-java#104]
@adityasaky Hey I just noticed that the files in 0.2 directory reference to the 0.1 spec in comments and most importantly in the [pedicateType](https://github.com/in-toto/in-toto-java/blob/master/src/main/java/io/github/intoto/slsa/models/v02/Provenance.java#L112). Should these refer to the 0.2 version?

**Comment by adityasaky** [comment]
Yep! Good eye, we should fix that ASAP.

**Comment by adityasaky** [comment]
@lakshya8066

**Comment by lakshya8066** [comment]
On it @adityasaky

**Comment by lakshya8066** [comment]
There might be more such cases. I will analyzing the files and update the PR. 
Also looking at why the tests are failing for me locally...

**Comment by lakshya8066** [comment]
@adityasaky This issue is fixed in another [PR](https://github.com/in-toto/in-toto-java/pull/130), it looks safe to close this.

**Comment by adityasaky** [comment]
thanks!
