### ISSUE TITLE
Access Denied error when running "mvn test"

### ISSUE THREAD

**Issue by m0jt4b4** [in-toto/in-toto-java#3]
I'll get follwoing error when runnig "mvn test" in travis-ci, which says access was denied:

[ERROR] Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.6: Could not transfer artifact org.apache.maven.plugins:maven-resources-plugin:pom:2.6 from/to central (https://repo.maven.apache.org/maven2): Access denied to: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom , ReasonPhrase:Forbidden. -> [Help 1]

I temporarily use "sudo: true" in .travis.yml configuration file at 72b39c1 as a workaround. But this bug needs to be fixed in future.

https://github.com/in-toto/in-toto-java/blob/72b39c1bc8413c97dc4331d0a026c5b7c20182cd/.travis.yml#L2

**Comment by adityasaky** [comment]
I think we can close this now.
